export const selects = {
    rooms: [],
    allDevices: [],
    dimmingDevices: [],
    entryTypes: [
        { id: 'device', name: 'Device' },
        { id: 'if', name: 'If' },
        { id: 'ifElse', name: 'If Else' },
        { id: 'wait', name: 'Wait' },
    ],
    triggerTypes: [
        { id: 'device', name: 'Device' },
        { id: 'sunset', name: 'Sunset' },
        { id: 'sunrise', name: 'Sunrise' },
        { id: 'time', name: 'Time' },
    ],
    deviceTypes: [
        { id: 'button', name: 'Button' },
        { id: 'dimmer', name: 'Dimmer' },
        { id: 'door', name: 'Door' },
        { id: 'garage', name: 'Garage' },
        { id: 'multioutlet', name: 'Multi Outlet' },
        { id: 'outlet', name: 'Outlet' },
        { id: 'sensor', name: 'Sensor' },
        { id: 'switch', name: 'Switch' },
    ],
    brightness: [
        { id: '100', name: '10%' },
        { id: '200', name: '20%' },
        { id: '300', name: '30%' },
        { id: '400', name: '40%' },
        { id: '500', name: '50%' },
        { id: '600', name: '60%' },
        { id: '700', name: '70%' },
        { id: '800', name: '80%' },
        { id: '900', name: '90%' },
        { id: '1000', name: '100%' },
    ],
    images: [
        { id: 'sensor', name: 'Sensor' },
        { id: 'tree-christmas', name: 'Christmas Tree' },
        { id: 'lights-holiday', name: 'Christmas Lights' },
        { id: 'light-ceiling', name: 'Ceiling Light' },
        { id: 'chevron-circle-right', name: 'Button' },
        { id: 'fan-table', name: 'Fan' },
        { id: 'door-closed', name: 'Door' },
        { id: 'garage', name: 'Garage' },
        { id: 'lamp', name: 'Small Lamp' },
        { id: 'outlet', name: 'Outlet' },
        { id: 'lamp-floor', name: 'Large Lamp' },
        { id: 'lightbulb', name: 'Lightbulb' },
        { id: 'speakers', name: 'Spearkes' },
    ],
    numOutlets: [
        { id: 1, name: '1' },
        { id: 2, name: '2' },
        { id: 3, name: '3' },
        { id: 4, name: '4' },
        { id: 5, name: '5' },
    ],
}
export const setRooms = rooms => (selects.rooms = rooms)
export const setAllDevices = devices => (selects.allDevices = devices)
export const setDimmingDevices = devices => (selects.dimmingDevices = devices)
